### ISSUE TITLE
Elevator Stucks at Starting CM4 core.

### ISSUE THREAD

**Issue by gencay3535** [NXP/mcu-smhmi#5]
Hello,

I have the SLN_TLHMI-IOT board. I can build the elevator project bootloader and the project itself without a problem. Only below two warnings:
`
Invalid project path: Include path not found (sln_smart_tlhmi_elevator_cm4\local_voice).
Invalid project path: Include path not found (sln_smart_tlhmi_elevator_cm7\sounds).	sln_smart_tlhmi_elevator_cm7
`
After I flash bootloader via an MCU-Link, I Flash the .axf file for the cm7 project. Then I restart the board but it stucks at 

````
0 0 [BOOTLOADER_Task] 

*** BOOTLOADER v1.1.0 ***

1 0 [BOOTLOADER_Task] Jumping to main application...

2 0 [BOOTLOADER_Task] [FICA] VERSION 3

3 0 [BOOTLOADER_Task] [FICA] RT Flash Check...

4 0 [BOOTLOADER_Task] [FICA] Found Flash device!

5 0 [BOOTLOADER_Task] [FICA] Checking Image Config Area (ICA) initialization

6 0 [BOOTLOADER_Task] [FICA] Flash ICA already initialized

7 0 [BOOTLOADER_Task] [FICA] Flash ICA initialization complete

8 0 [BOOTLOADER_Task] Launching into application at 0x30100000

Starting CM4 core.

````

**Comment by SavaAlexandru** [comment]
Hello gencay3535,
Can you tell us what is the current MCUXpresso version that you have?
Because of an error within the toolchain we support only 11.5.0 and with next release 11.7.0.

**Comment by gencay3535** [comment]
I have the v11.7.0

**Comment by SavaAlexandru** [comment]
> I have the v11.7.0
For v11.7.0 did you enable manage scripter link in the cm4 ?
right click cm4 project->Properties -> c/c++ Build -> Settings -> MCU C++ Linker -> Managed Linker Script
Thick the Manage linker script 
Also please Clean the project and delete the Debug/Release folder
![image](https://user-images.githubusercontent.com/84315390/215732160-a68f9ae0-9abe-4ff2-8beb-0276ca79da49.png)

**Comment by gencay3535** [comment]
Thank you this solved the issue for me. 

- May I ask how can I add the related resources because now, images are not included.
- One other thing is, how can I start developing on this board without a bootloader, since for now we are using the sdk for the evk so sdram, flash and some of other things are different that's why I can't run lvgl examples on this board. Where should I start to adjust my environment to work on this board, some similar process will be required for my custom board at the end.

**Comment by SavaAlexandru** [comment]
To add the resources. Flash them at the address 0x3070_0000 the resources are found at the path [mcu-smhmi](https://github.com/NXP/mcu-smhmi)/[elevator](https://github.com/NXP/mcu-smhmi/tree/master/elevator)/resource/[elevator_resource.bin](https://github.com/NXP/mcu-smhmi/blob/master/elevator/resource/elevator_resource.bin)

In order to not use the bootloader you need to:
- modify the flash address for the cm7 from 0x3010_0000 to 0x3000_0000. This will automatically add the boot header to the final image.
- in fica_definition.h you need to modify the FICA_IMG_BOOTLOADER_SIZE to 0x0
- The resource should be placed at 0x3060_0000
